### ISSUE TITLE
Software Model Chosen + Justifications

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/3354-Group1#4]

**Comment by kylepo99** [comment]
We chose the Model-View-Controller (MVC) architecture pattern for our textbook selling
application, because of its flexibility, ease of scalability, and efficient handling of server
communication.

The platform will need to support a wide variety of user roles, such as sellers, renters, and partnered book suppliers. Each of these users has different needs and would require different interfaces. For example, sellers would need a view to create and manage their listings, while renters would need a view to browse and purchase available textbooks. MVC allows us to easily accomplish this because the View component is completely separated from any other logic, allowing us to create unique views as needed. The Controller component provides a shared set of modules for managing user input and processing requests, such as handling form submissions and routing requests to the appropriate views. This streamlines development of views as we don't have to recreate the same modules and logic for each view; rather, they can be shared as needed.

Since our platform is a mobile application that relies heavily on user interaction, frequent communication occurs between the user-facing application and the backend database as users create listings, purchase products, and leave reviews. The MVC architecture supports these interactions by allowing the View (User Interface) to communicate with the Model (Database) through the Controller. When a user interacts with the View, the Controller handles the input, updates the Model if necessary, and then updates the View to reflect any changes. This ensures that the user sees the most up-to-date information. Additionally, the centralized Model is important for maintaining data consistency between users, especially when multiple users are viewing or purchasing a single product. By keeping the data in a single, centralized location, MVC ensures that all users see the same information and reduces the risk of data inconsistencies.

Scalability is important for our platform, as we typically see spikes in demand following the end of a school year when students sell off their old books, and similarly at the beginning of the school year when students are purchasing books. The MVC architecture enables us to handle these seasonal spikes effectively by allowing us to scale the backend (Model) component independently. For example, during a spike in purchasing activity, we can scale up the number of instances of the Model component to handle the increased load on the database. This flexibility allows us to optimize our resource allocation and reduce costs by only scaling the components that are under strain. Additionally, because the architecture separates the Model from the View and Controller, we can preform this scaling without affecting the user experience or local components running on individual devices. This separation ensures overall system stability and performance.
